### ISSUE TITLE
Quelldaten

### ISSUE THREAD

**Issue by Chaot1** [MrDrache333/iobroker-tankerkoenig-grafana-dashboard#3]
Welche Daten muss ich im ioBroker in die Datenbank schreiben? Kannst du das eventuell noch mit angeben?

Sieht übrigens total klasse aus. Danke dafür.

**Comment by Hilti23** [comment]
Das würde mich auch interessieren :)

**Comment by MrDrache333** [comment]
Das kommt darauf an, wieviele Stationen du in dem Dashboard hinzugefügt hast. Das Dashboard verwendet einmal den Preis (short), den Namen(name) und den "geöffnet" Status(status). Der Preis ist dann abhängig von der gewählten Kraftstoffart.
